# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ExampleObjc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleObjc
  pod 'NFCPassportReader', :path => '../'
  pod 'QKMRZScanner'

  target 'ExampleObjcTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleObjcUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
